# Generated by Django 5.2.4 on 2025-09-25 12:59

import backend.apps.bookings.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(validators=[backend.apps.bookings.validators.validate_time_step])),
                ('end_datetime', models.DateTimeField(validators=[backend.apps.bookings.validators.validate_time_step])),
                ('visitors_count', models.PositiveSmallIntegerField(validators=[backend.apps.bookings.validators.validate_visitors_count])),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
            ],
        ),
    ]
