# Generated by Django 5.2.4 on 2025-07-29 10:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
        migrations.CreateModel(
            name='SaunaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default=datetime.time(8, 0))),
                ('closing_time', models.TimeField(default=datetime.time(0, 0))),
                ('max_visitors_count', models.PositiveSmallIntegerField(default=4)),
                ('min_time_from_now_to_booking', models.DurationField(default=datetime.timedelta(seconds=9000))),
                ('min_booking_time', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('min_time_between_bookings', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('check_30_min_multiplicity', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
