# Generated by Django 5.2.4 on 2025-07-29 13:07

import datetime
from django.db import migrations


def create_default_pricing(apps, schema_editor):
    pricing_model = apps.get_model('core', 'Pricing')
    pricing_model.objects.create(
        name='hourly_rent',
        description='Цена аренды за 1 час',
        price=5000
    )
    pricing_model.objects.create(
        name='prepayment',
        description='Сумма предоплаты за бронирование',
        price=2000.00
    )


def create_default_sauna_config(apps, schema_editor):
    sauna_config_model = apps.get_model('core', 'SaunaConfig')
    sauna_config_model.objects.create(
        opening_time = datetime.time(8),
        closing_time = datetime.time(0),
        max_visitors_count = 4,
        min_time_from_now_to_booking = datetime.timedelta(hours=2, minutes=30),
        min_booking_time = datetime.timedelta(hours=2),
        min_time_between_bookings = datetime.timedelta(hours=1),
        check_30_min_multiplicity = True
    )



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_pricing),
        migrations.RunPython(create_default_sauna_config),
    ]
