# Generated by Django 5.2.4 on 2025-08-09 18:33

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_default_pricing(apps: Apps, _: BaseDatabaseSchemaEditor) -> None:
    pricing_model = apps.get_model("core", "Pricing")
    pricing_model.objects.create(
        name="hourly_rent", description="Цена аренды за 1 час", price=5000
    )
    pricing_model.objects.create(
        name="prepayment", description="Сумма предоплаты за бронирование", price=2000.00
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_sauna_config_data"),
    ]

    operations = [
        migrations.RunPython(create_default_pricing),
    ]
