# Generated by Django 5.2.4 on 2025-08-09 18:33

from django.db import migrations


def create_default_pricing(apps, schema_editor):
    pricing_model = apps.get_model('core', 'Pricing')
    pricing_model.objects.create(
        name='hourly_rent',
        description='Цена аренды за 1 час',
        price=5000
    )
    pricing_model.objects.create(
        name='prepayment',
        description='Сумма предоплаты за бронирование',
        price=2000.00
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_sauna_config'),
    ]

    operations = [
        migrations.RunPython(create_default_pricing),
    ]
