# Generated by Django 5.2.4 on 2026-02-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_pricing_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaunaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/sauna_gallery')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
