# Generated by Django 5.2.4 on 2025-11-17 18:13

import backend.validators.django_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[backend.validators.django_validators.validate_phone_number])),
                ('last_visit_date', models.DateField()),
                ('number_of_visits', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
