name: Lint Coded Base

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run ESlint
        working-directory: ./frontend
        run: npx eslint .

      - name: Run Prettier
        working-directory: ./frontend
        run: npx prettier --check .
